apiVersion: apps/v1
kind: Deployment
metadata:
  name: small
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default
    spec:
      tolerations:
      - key: "karpenter/taint"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: reserved-first
        image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
        resources:
          requests:
            cpu: 900m