apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 1s
  template:
    metadata:
      labels:
        instance-type: large
        cost: high
        nodepool: default
    spec:
      expireAfter: 10h0m0s
      taints:
        - key: karpenter/taint
          effect: NoSchedule
      nodeClassRef:
        group: karpenter.k8s.aws
        name: default
        kind: EC2NodeClass
      requirements:
      - key: "karpenter.k8s.aws/instance-category"
        operator: In
        values: ["c", "m", "r"]
      - key: "karpenter.k8s.aws/instance-generation"
        operator: Gt
        values: ["4"]
      - key: "kubernetes.io/os"
        operator: In
        values:
        - linux
      - key: "kubernetes.io/arch"
        operator: In
        values:
        - amd64
      - key: "karpenter.sh/capacity-type"
        operator: In
        values:
        - on-demand
  weight: 10